
COMPONENT_SRCDIRS := src src/util
COMPONENT_ADD_INCLUDEDIRS := include
COMPONENT_PRIV_INCLUDEDIRS := src/port/esp8266 src/util

ifndef CONFIG_HTTPD_WS_SUPPORT
COMPONENT_OBJEXCLUDE += src/httpd_ws.o
endif
